### ISSUE TITLE
针对中文纠错，运行gradio_demo.py文件报错问题

### ISSUE THREAD

**Issue by huangding1535** [shibing624/lmft#12]
报错问题打印如下：
Traceback (most recent call last):
  File "gradio_demo.py", line 15, in <module>
    model = model.half().cuda()
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 750, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/aiuser/.conda/envs/ChatGLM_Train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 750, in <lambda>
    return self._apply(lambda t: t.cuda(device))
NotImplementedError: Cannot copy out of meta tensor; no data!

---------------------------------------------------------------------------------------------------------------------------------
楼主帮忙看下是什么问题

**Comment by shibing624** [comment]
你check下自己的gpu环境，支持fp16吗，gpu是啥型号，3090吗？

**Comment by huangding1535** [comment]
另外，输出能支持流式的吗

**Comment by shibing624** [comment]
调用用官方的默认stream chat就可以

**Comment by huangding1535** [comment]
好的，感谢。
