### ISSUE TITLE
训练完成最后一次保存会报错，之前每个epoch的保存没有问题

### ISSUE THREAD

**Issue by xiaoranchenwai** [shibing624/lmft#3]
Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████| 18510/18510 [1:03:54<00:00,  4.18it/s]
  File "training_chatglm_demo.py", line 97, in <module>
    finetune_demo()
  File "training_chatglm_demo.py", line 64, in finetune_demo
    model.train_model(train_df)
  File "/home/user/cx/lmft-main/lmft/chatglm_model.py", line 323, in train_model
    self.save_model(model=self.model)
  File "/home/user/cx/lmft-main/lmft/chatglm_model.py", line 480, in save_model
    self.tokenizer.save_pretrained(output_dir)
  File "/home/user/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2174, in save_pretrained
    save_files = self._save_pretrained(
  File "/home/user/anaconda3/envs/pytorch1.13/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2222, in _save_pretrained
    vocab_files = self.save_vocabulary(save_directory, filename_prefix=filename_prefix)
  File "/home/user/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 301, in save_vocabulary
    save_directory, VOCAB_FILES_NAMES["vocab_file"]
NameError: name 'VOCAB_FILES_NAMES' is not defined

**Comment by shibing624** [comment]
chatglm原代码的bug，把tokenization_chatglm.py 301行的改为：self.vocab_files_names 就可以。
```
300 if os.path.isdir(save_directory):
301             vocab_file = os.path.join(
302                 save_directory, self.vocab_files_names["vocab_file"]                                                                                 
303             )
```

我比较了下，发现THUDM--chatglm-6b-int4-qe/ 是对的，我这边下载的THUDM--chatglm-6b也是对的，只有THUDM--chatglm-6b-int4 模型的tokenization_chatglm.py是错误的。

**Comment by xiaoranchenwai** [comment]
好的，谢谢
